### ISSUE TITLE
Code availability?

### ISSUE THREAD

**Issue by Zhanwei-Z** [InhwanBae/EigenTrajectory#2]
Thank you for sharing the great prediction method. When is the code going to be available?

**Comment by InhwanBae** [comment]
Hi @Zhanwei-Z, I'm currently working on finalizing it. I'll let you know as soon as it's ready for release. Please stay tuned!

**Comment by InhwanBae** [comment]
Hi @Zhanwei-Z, I just released the source code. Check it out!

**Comment by Zhanwei-Z** [comment]
Thank you for sharing your excellent code. Are there any plans to release code that supports the SDD and GCS datasets?

**Comment by Zhanwei-Z** [comment]
> Hi @Zhanwei-Z, I just released the source code. Check it out!


Thank you for sharing your excellent code. Are there any plans to release code that supports the SDD and GCS datasets?

**Comment by InhwanBae** [comment]
Hi @Zhanwei-Z,
We used the same code for both the SDD and GCS datasets. Instead, we convert the SDD and GCS datasets into the ETH/UCY format. For SDD, we imported the Y-Net's trajnet split and extracted text files for each scene. As for the GCS dataset, we processed the original dataset for use. please refer [here](https://github.com/InhwanBae/NPSN/issues/5) for more details.

**Comment by Zhanwei-Z** [comment]
> Hi @Zhanwei-Z, We used the same code for both the SDD and GCS datasets. Instead, we convert the SDD and GCS datasets into the ETH/UCY format. For SDD, we imported the Y-Net's trajnet split and extracted text files for each scene. As for the GCS dataset, we processed the original dataset for use. please refer [here](https://github.com/InhwanBae/NPSN/issues/5) for more details.

Thank you for your response. Could you please provide the processed datasets for SDD and GCS?
