### ISSUE TITLE
GCS dataset?

### ISSUE THREAD

**Issue by Carrotsniper** [InhwanBae/EigenTrajectory#4]
Thanks for your amazing work, I am wondering that where can I download the GCS dataset
mentioned in your paper?

**Comment by InhwanBae** [comment]
Hi @Carrotsniper,

Thanks for your interest in my work! 
Here is the link for the [GCS dataset](https://www.dropbox.com/s/7y90xsxq0l0yv8d/cvpr2015_pedestrianWalkingPathDataset.rar?dl=0) provided by this [GitHub](https://github.com/svip-lab/CIDNN/tree/master?tab=readme-ov-file#dataset).
For the dataset preprocessing, please take a look at [this issue](https://github.com/InhwanBae/NPSN/issues/5).

**Comment by Carrotsniper** [comment]
Hi Inhwan, 

Thanks for your very quick reply, I will go have a try.

**Comment by Carrotsniper** [comment]
Hi Inhwan, thanks for your very quick reply, which is quite helpful.
