### ISSUE TITLE
How should I determine the corresponding "static_dist"

### ISSUE THREAD

**Issue by cycal1020** [InhwanBae/EigenTrajectory#5]
Thank you for your work!

When I was downloading the pretrained model file, I found that different datasets have a corresponding "static.dist" coefficient, such as the ETH dataset's "static.dist": 0.419, the ZARA1 dataset's "static.dist": 0.338, and so on. Now I want to use the SDD dataset for training. How should I determine the corresponding "static_dist"? How much is it confirmed?

Looking forward to your reply！

**Comment by InhwanBae** [comment]
Hi @cycal1020 ,

I set the `static_dist` parameter to `0.326` in the SDD dataset. This parameter is essential to avoid issues with normalizing stationary trajectories, as it prevents division by zero or excessively large numbers. In my experience, this number doesn't affect performance all that much. For example, it almost doesn't matter if you enter `0.327` or `0.328`.
If you have any further questions, feel free to ask!

**Comment by InhwanBae** [comment]
Oh, I forgot to tell you that when loading the SDD dataset, I divided it by 20. Since SDD is in pixel coordinates, to match the distribution similar to ETH/UCY, you should divide `obs_traj` and `pred_traj` by `20`, or multiply `static_dist` by `20`.
